spring:
  application:
    name: Application
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    password: user
    username: user
    virtual_host: local




